<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.16.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CollegeManagement.Common\CollegeManagement.Common.csproj" />
    <ProjectReference Include="..\CollegeManagement.Data\CollegeManagement.Data.csproj" />
    <ProjectReference Include="..\CollegeManagement.Service\CollegeManagement.Service.csproj" />
    <ProjectReference Include="..\CollegeManagement.Store\CollegeManagement.Store.csproj" />
  </ItemGroup>

</Project>
